languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Jorrit Gorseman"
# logo = "img/logo.jpg"
description = "The website of Jorrit Gorseman."
copyright = "&copy; 2023 Jorrit Gorseman"

dateFormat = "2 January 2006"

[author]
  name = "Jorrit Gorseman"
  image = "img/author.jpg"
  headline = "QA engineer in the Netherlands"
  bio = "Hi, my name is Jorrit Gorseman. I work as a QA engineer in the Netherlands and I'm passionate about al things quality, whether it's products, people or processes. On this site I share what I'm learning along the way."
  links = [
    { email= "mailto:jorrit.gorseman@gmail.com" },
    { linkedin = "https://www.linkedin.com/in/jorritgorseman/" },
    { github = "https://github.com/jgorseman" },
    { facebook = "https://www.facebook.com/jgorseman/" },
  ]
